services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
  
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - '8001:8001'
    depends_on:
      - dynamodb-local
    networks:
      - default

  lambda-apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lambda-apigateway
    working_dir: /usr/src/app
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - dynamodb-local
    networks:
      - default
    tty: true
    stdin_open: true

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger/openapi.yaml
    volumes:
      - ./documents/swagger:/swagger
    networks:
      - default

networks:
  default:
    driver: bridge
